[package]
name = "serde_yaml"
version = "0.8.21" # remember to update html_root_url, and readme for major versions
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
rust-version = "1.38"
license = "MIT OR Apache-2.0"
description = "YAML support for Serde"
repository = "https://github.com/dtolnay/serde-yaml"
documentation = "https://docs.rs/serde_yaml/"
readme = "README.md"
keywords = ["yaml", "serde"]

[dependencies]
dtoa = "0.4"
indexmap = "1.5"
serde = "1.0.69"
yaml-rust = {git = "https://github.com/dchakrav-github/yaml-rust"}

[dev-dependencies]
anyhow = "1.0"
indoc = "1.0"
serde_derive = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
